In [4]:
import os
from dotenv import load_dotenv
from google import genai

# Cargar variables del archivo .env
load_dotenv()

# Obtener la clave
api_key = os.getenv("GEMINI_API_KEY")

# Inicializa el cliente
client = genai.Client()

# Genera contenido utilizando el modelo recomendado
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Cual y cuando fue el primer computador?",
)

print(response.text)

La pregunta sobre cuál fue el "primer computador" es compleja, ya que la definición de "computador" ha evolucionado con el tiempo, desde máquinas mecánicas hasta electrónicas, y desde las de propósito específico hasta las de propósito general.

Aquí te presento las principales máquinas consideradas "primeras" en diferentes categorías:

1.  **El primer concepto de computador programable (mecánico):**
    *   **Cuál:** La **Máquina Analítica** de Charles Babbage.
    *   **Cuándo:** Diseñada en la década de **1830** (específicamente entre 1833 y 1842), aunque nunca fue completamente construida en su tiempo debido a limitaciones tecnológicas y financieras.
    *   **Por qué es importante:** Incorporó muchos de los elementos esenciales de un computador moderno: una "unidad de procesamiento" (el molino), una "memoria" (el almacén), entrada y salida, y la capacidad de ser programada usando tarjetas perforadas. Ada Lovelace escribió los primeros algoritmos para esta máquina, convirtiéndose en la primera programadora.

2.  **El primer computador programable completamente funcional (electromecánico):**
    *   **Cuál:** El **Z3** de Konrad Zuse (Alemania).
    *   **Cuándo:** Completado en **1941**.
    *   **Por qué es importante:** Fue el primer computador completamente funcional y programable del mundo, usando relés electromecánicos. Era digital y podía realizar cálculos complejos, aunque fue destruido en los bombardeos de Berlín en 1943.

3.  **El primer computador digital electrónico (no programable en el sentido moderno):**
    *   **Cuál:** El **Atanasoff-Berry Computer (ABC)**, desarrollado por John Atanasoff y Clifford Berry en la Universidad Estatal de Iowa (EE. UU.).
    *   **Cuándo:** Completado en **1942**.
    *   **Por qué es importante:** Fue el primer computador digital electrónico automático. Usaba tubos de vacío para la computación y memoria regenerativa, pero no era un computador de propósito general; estaba diseñado para resolver sistemas de ecuaciones lineales.

4.  **El primer computador electrónico programable (de propósito específico):**
    *   **Cuál:** El **Colossus** (Reino Unido).
    *   **Cuándo:** La primera versión, Colossus Mark 1, entró en funcionamiento en **1943**. El Colossus Mark 2 en **1944**.
    *   **Por qué es importante:** Desarrollado en secreto por los británicos (con figuras como Alan Turing y Tommy Flowers) durante la Segunda Guerra Mundial, fue diseñado para descifrar los mensajes cifrados alemanes (códigos Lorenz). Fue el primer computador electrónico programable, pero su programación se realizaba mediante interruptores y cables, y no era de propósito general.

5.  **El primer computador electrónico digital de propósito general (la respuesta más común):**
    *   **Cuál:** El **ENIAC (Electronic Numerical Integrator and Computer)**, desarrollado por John Mauchly y J. Presper Eckert en la Universidad de Pensilvania (EE. UU.).
    *   **Cuándo:** Fue presentado oficialmente en **1946** (aunque su desarrollo comenzó en 1943).
    *   **Por qué es importante:** Es ampliamente considerado el *primer computador electrónico digital de propósito general*. Era una máquina enorme, pesaba 27 toneladas y usaba más de 17,000 tubos de vacío. Podía ser reprogramada para realizar una amplia gama de tareas numéricas, marcando el comienzo de la era de la computación electrónica moderna y de propósito general.

**En resumen:**

Si nos referimos al **primer computador electrónico digital de propósito general**, la respuesta más aceptada es el **ENIAC**, presentado en **1946**. Sin embargo, es crucial reconocer a sus predecesores conceptuales y funcionales que sentaron las bases.

In [ ]:
contents = ['En mi facultad tenemos 4 carreras, la carrera de Ingeniería en Computación, Ingeniería en Software, Ingeniería en sistemas de la Información e Ingeniería en Ciencias de Datos e Inteligencia Artificial'
            'Las matriculas para el proximo semestre comienzan el 1 de julio y terminan el 15 de julio. Es importante que los estudiantes se matriculen en la fecha correspondiente a su carrera'
            '']

## Integración llm con sistema de recuperación de la información de embeddings

In [3]:
import pandas as pd
import kagglehub
data_path = kagglehub.dataset_download("stefanoleone992/rotten-tomatoes-movies-and-critic-reviews-dataset")

movies_path = data_path + '\\' + 'rotten_tomatoes_movies.csv'
movies = pd.read_csv(movies_path)
reviews_path = data_path + '\\' + 'rotten_tomatoes_critic_reviews.csv'
reviews = pd.read_csv(reviews_path)

In [10]:
print(f"Movies: {movies.shape}")
print(f"Reviews: {reviews.shape}")

Movies: (17712, 22)
Reviews: (1130017, 8)

In [26]:
movies.head(2)

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
1,m/0878835,Please Give,Kate (Catherine Keener) and her husband Alex (...,Nicole Holofcener's newest might seem slight i...,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",2010-04-30,...,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19

In [20]:
reviews.head(2)

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."

In [24]:
df = movies.merge(
    reviews[[
        "rotten_tomatoes_link",
        "critic_name",
        "publisher_name",
        "review_type",
        "review_score",
        "review_content"
    ]],
    on="rotten_tomatoes_link",
    how="left"
)

In [25]:
df.head(5)

,rotten_tomatoes_link,movie_title,movie_info,critics_consensus,content_rating,genres,directors,authors,actors,original_release_date,...,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count,critic_name,publisher_name,review_type,review_score,review_content
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,53.0,254421.0,43,73,76,Andrew L. Urban,Urban Cinefile,Fresh,NaN,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,53.0,254421.0,43,73,76,Louise Keller,Urban Cinefile,Fresh,NaN,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,53.0,254421.0,43,73,76,NaN,FILMINK (Australia),Fresh,NaN,With a top-notch cast and dazzling special eff...
3,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,53.0,254421.0,43,73,76,Ben McEachen,Sunday Mail (Australia),Fresh,3.5/5,Whether audiences will get behind The Lightnin...
4,m/0814255,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",Though it may seem like just another Harry Pot...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,...,53.0,254421.0,43,73,76,Ethan Alter,Hollywood Reporter,Rotten,NaN,What's really lacking in The Lightning Thief i...

In [30]:
df["document"] = (
    df["movie_title"].fillna("") + " " +
    df["movie_info"].fillna("") + " " +
    df["content_rating"].fillna("") + " " +
    df["genres"].fillna("") + " " +
    df["directors"].fillna("") + " " +
    df["authors"].fillna("") + " " +
    df["actors"].fillna("") + " " +
    df["original_release_date"].fillna("") + " " +
    df["runtime"].fillna("").astype(str) + " " +
    df["production_company"].fillna("")
).str.strip()

In [42]:
df = df[df["document"] != ""].reset_index(drop=True)
print(len(df))
df["document"].head(5)

1129893

0    Percy Jackson & the Olympians: The Lightning T...
1    Percy Jackson & the Olympians: The Lightning T...
2    Percy Jackson & the Olympians: The Lightning T...
3    Percy Jackson & the Olympians: The Lightning T...
4    Percy Jackson & the Olympians: The Lightning T...
Name: document, dtype: str

In [39]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)

True

In [44]:
import re

stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    """
    Preprocesamiento básico para el corpus.
    - Conversión a minúsculas
    - Eliminación de puntuación
    - Eliminación de espacios redundantes
    """
    if not isinstance(text, str):
        return ""
    text = text.lower()                          # minúsculas
    text = re.sub(r"[^\w\s]", "", text)          # eliminar puntuación
    text = re.sub(r"\s+", " ", text).strip()     # espacios redundantes

    words = text.split()
    words = [w for w in words if w not in stop_words]

    # 6. Lematización
    words = [lemmatizer.lemmatize(w) for w in words]

    # 7. Unir de vuelta a string
    return " ".join(words)

In [52]:
df = df.sample(frac= 0.1, random_state=42).reset_index(drop=True)

# Aplicar preprocesamiento a la columna document
df["document"] = df["document"].apply(preprocess)

print(f"Documentos para indexar: {len(df)}")
print(f"\nEjemplo preprocesado:\n{df['document'].iloc[0:10]}")

Documentos para indexar: 22598

Ejemplo preprocesado:
0    wrinkle time meg murry little brother charles ...
1    kickass using love comic inspiration teenager ...
2    hunger focusing 1981 hunger strike republican ...
3    green book dr shirley worldclass africanameric...
4    crazy rich asian rachel chu happy accompany lo...
5    undisputed tell story undefeated worldchampion...
6    inferno famous symbologist robert langdon tom ...
7    guarding tess doug chesnic nicolas cage agent ...
8    enemy gate vassili jude law young russian shar...
9    nicotina hacker spying pretty neighbor mess as...
Name: document, dtype: str

In [53]:
from sentence_transformers import SentenceTransformer
import numpy as np

# 1. Cargar modelo preentrenado
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# 2. Lista de documentos preprocesados
documents = df["document"].tolist()

# 3. Generar embeddings
print("Calculando embeddings...")
embeddings = model.encode(documents, batch_size=120, show_progress_bar=True)
embeddings = np.array(embeddings)

print(f"Shape de embeddings: {embeddings.shape}")

# 4. Guardar en disco para no recalcular
np.save("embeddings_minilm.npy", embeddings)
print("Embeddings guardados en embeddings_minilm.npy")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 19217.67it/s]

Calculando embeddings...

Batches: 100%|██████████| 189/189 [05:58<00:00,  1.90s/it]

Shape de embeddings: (22598, 384)
Embeddings guardados en embeddings_minilm.npy

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

def search_model(query, model, embeddings, df, k=5):
    query_processed = preprocess(query)
    query_embedding = model.encode([query_processed])

    similarities = cosine_similarity(query_embedding, embeddings)[0]
    top_k_idx = similarities.argsort()[::-1][:k]

    results = []

    for rank, idx in enumerate(top_k_idx, start=1):
        results.append({
            "Ranking": rank,
            "ID": df["rotten_tomatoes_link"].iloc[idx],
            "Título": df["movie_title"].iloc[idx],
            "Información": df["movie_info"].iloc[idx],
            "Clasificación": df["content_rating"].iloc[idx],
            "Géneros": df["genres"].iloc[idx],
            "Directores": df["directors"].iloc[idx],
            "Autores": df["authors"].iloc[idx],
            "Actores": df["actors"].iloc[idx],
            "Fecha estreno": df["original_release_date"].iloc[idx],
            "Duración": df["runtime"].iloc[idx],
            "Productora": df["production_company"].iloc[idx],
            "Similitud": round(float(similarities[idx]), 4)
        })

    return pd.DataFrame(results)

In [55]:
query = "science fiction movie with advanced technology"

In [61]:
embeddings_a = embeddings
results = search_model(query, model, embeddings_a, df, k=100)
display(results)

,Ranking,ID,Título,Información,Clasificación,Géneros,Directores,Autores,Actores,Fecha estreno,Duración,Productora,Similitud
0,1,m/mystery_science_theater_3000_the_movie,Mystery Science Theater 3000: The Movie,Dr. Clayton Forrester (Trace Beaulieu) figures...,PG-13,"Comedy, Science Fiction & Fantasy, Special Int...",Jim Mallon,"Michael J. Nelson, Mary Jo Pehl, Bridget Jones...","Michael J. Nelson, Trace Beaulieu, Jim Mallon,...",1996-04-19,73.0,MCA Universal Home Video,0.5139
1,2,m/mystery_science_theater_3000_the_movie,Mystery Science Theater 3000: The Movie,Dr. Clayton Forrester (Trace Beaulieu) figures...,PG-13,"Comedy, Science Fiction & Fantasy, Special Int...",Jim Mallon,"Michael J. Nelson, Mary Jo Pehl, Bridget Jones...","Michael J. Nelson, Trace Beaulieu, Jim Mallon,...",1996-04-19,73.0,MCA Universal Home Video,0.5139
2,3,m/mystery_science_theater_3000_the_movie,Mystery Science Theater 3000: The Movie,Dr. Clayton Forrester (Trace Beaulieu) figures...,PG-13,"Comedy, Science Fiction & Fantasy, Special Int...",Jim Mallon,"Michael J. Nelson, Mary Jo Pehl, Bridget Jones...","Michael J. Nelson, Trace Beaulieu, Jim Mallon,...",1996-04-19,73.0,MCA Universal Home Video,0.5139
3,4,m/titan_ae,Titan A.E.,A science-fiction film that combines tradition...,PG,"Animation, Kids & Family, Science Fiction & Fa...","Don Bluth, Gary Goldman","Ben Edlund, John August, Joss Whedon","Matt Damon, Bill Pullman, Drew Barrymore, John...",2000-06-16,95.0,20th Century Fox,0.5027
4,5,m/titan_ae,Titan A.E.,A science-fiction film that combines tradition...,PG,"Animation, Kids & Family, Science Fiction & Fa...","Don Bluth, Gary Goldman","Ben Edlund, John August, Joss Whedon","Matt Damon, Bill Pullman, Drew Barrymore, John...",2000-06-16,95.0,20th Century Fox,0.5027
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,m/southland_tales,Southland Tales,With the United States under the threat of nuc...,R,"Comedy, Musical & Performing Arts, Mystery & S...",Richard Kelly,Richard Kelly,"Seann William Scott, Sarah Michelle Gellar, Cu...",2007-09-22,144.0,Samuel Goldwyn Films,0.3816
96,97,m/final_fantasy_the_spirits_within,Final Fantasy: The Spirits Within,Blurring the lines between reality and compute...,PG-13,"Animation, Science Fiction & Fantasy","Hironobu Sakaguchi, Motonori Sakakibara, Jack ...","Hironobu Sakaguchi, Al Reinert, Jeff Vintar","Ming-Na Wen, Alec Baldwin, Ving Rhames, Steve ...",2001-07-11,106.0,Columbia Pictures,0.3798
97,98,m/final_fantasy_the_spirits_within,Final Fantasy: The Spirits Within,Blurring the lines between reality and compute...,PG-13,"Animation, Science Fiction & Fantasy","Hironobu Sakaguchi, Motonori Sakakibara, Jack ...","Hironobu Sakaguchi, Al Reinert, Jeff Vintar","Ming-Na Wen, Alec Baldwin, Ving Rhames, Steve ...",2001-07-11,106.0,Columbia Pictures,0.3798
98,99,m/robot_overlords,Robot Overlords,"After the Earth is conquered by alien robots, ...",PG-13,"Action & Adventure, Science Fiction & Fantasy",Jon Wright,"Jon Wright, Mark Stay","Ben Kingsley, Gillian Anderson, Callan McAulif...",2015-07-03,89.0,Vertical Entertainment,0.3783
99,100,m/the_lobster,The Lobster,"In a dystopian society, single people must fin...",R,"Comedy, Cult Movies, Drama, Science Fiction & ...",Yorgos Lanthimos,"Yorgos Lanthimos, Efthimis Filippou","Colin Farrell, Rachel Weisz, Léa Seydoux, Ben ...",2016-05-13,118.0,A24 Films,0.3776

In [62]:
prompt = (
    f"Eres un chatbot coversacional. Mi usuario quiere saber sobre {query}, y mi sistema de recuperacion de la informacion encontro esto {results}."
    f"Dame la respuesta en base al contexto dado por el sistema de recuperacion de la informacion")

In [63]:
import os
from dotenv import load_dotenv
from google import genai

# Cargar variables del archivo .env
load_dotenv()

# Obtener la clave
api_key = os.getenv("GEMINI_API_KEY")

# Inicializa el cliente
client = genai.Client()

# Genera contenido utilizando el modelo recomendado
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt,
)

print(response.text)

Claro, basándome en la información proporcionada por el sistema de recuperación, aquí tienes algunas películas de ciencia ficción que involucran tecnología avanzada:

1.  **Titan A.E.** (Ranking 4, 5):
    *   **Información:** Es una película de ciencia ficción animada que se desarrolla en el año 3043, después de que la Tierra ha sido destruida. Esto implica la presencia de tecnología avanzada para la supervivencia espacial, naves interplanetarias y posiblemente armas futuristas, dada la necesidad de encontrar un nuevo hogar.
    *   **Géneros:** Animación, Ciencia Ficción y Fantasía.
    *   **Directores:** Don Bluth, Gary Goldman.
    *   **Año de estreno:** 2000.

2.  **Final Fantasy: The Spirits Within** (Ranking 97, 98):
    *   **Información:** Esta película destaca por "difuminar las líneas entre la realidad y la computación", ambientada en el año 2065, donde la Tierra está siendo devastada por invasores alienígenas. La trama sugiere la utilización de tecnología avanzada para combatir a los alienígenas y la propia naturaleza de su animación de vanguardia es un ejemplo de tecnología.
    *   **Géneros:** Animación, Ciencia Ficción y Fantasía.
    *   **Directores:** Hironobu Sakaguchi, Motonori Sakakibara, Jack Fletcher.
    *   **Año de estreno:** 2001.

3.  **Robot Overlords** (Ranking 99):
    *   **Información:** La premisa central es que la Tierra ha sido conquistada por robots alienígenas. Esto claramente sitúa la tecnología avanzada (robots, seguramente naves, sistemas de control, etc.) en el centro de la narrativa.
    *   **Géneros:** Acción y Aventura, Ciencia Ficción y Fantasía.
    *   **Director:** Jon Wright.
    *   **Año de estreno:** 2015.

Aunque otras películas como **Mystery Science Theater 3000: The Movie** (Ranking 1, 2, 3) se encuentran en el género de ciencia ficción y comedia, su descripción se centra más en una experimentación de un Dr. con películas que en tecnología avanzada en la trama principal. **The Lobster** (Ranking 100), aunque es ciencia ficción distópica, no detalla explícitamente tecnología avanzada en su sinopsis.

Espero que estas recomendaciones te sean útiles. ¡Avísame si quieres saber más sobre alguna de ellas!

In [64]:
from collections import deque

context = deque()

context.append(prompt)
context.append(response.text)
context.append("Ya pero cual de esas es mas antigua")
str(context)

'deque([\'Eres un chatbot coversacional. Mi usuario quiere saber sobre science fiction movie with advanced technology, y mi sistema de recuperacion de la informacion encontro esto     Ranking                                        ID  \\\\\\n0         1  m/mystery_science_theater_3000_the_movie   \\n1         2  m/mystery_science_theater_3000_the_movie   \\n2         3  m/mystery_science_theater_3000_the_movie   \\n3         4                                m/titan_ae   \\n4         5                                m/titan_ae   \\n..      ...                                       ...   \\n95       96                         m/southland_tales   \\n96       97        m/final_fantasy_the_spirits_within   \\n97       98        m/final_fantasy_the_spirits_within   \\n98       99                         m/robot_overlords   \\n99      100                             m/the_lobster   \\n\\n                                     Título  \\\\\\n0   Mystery Science Theater 3000: The Movie   \\n1   Mystery Science Theater 3000: The Movie   \\n2   Mystery Science Theater 3000: The Movie   \\n3                                Titan A.E.   \\n4                                Titan A.E.   \\n..                                      ...   \\n95                          Southland Tales   \\n96        Final Fantasy: The Spirits Within   \\n97        Final Fantasy: The Spirits Within   \\n98                          Robot Overlords   \\n99                              The Lobster   \\n\\n                                          Información Clasificación  \\\\\\n0   Dr. Clayton Forrester (Trace Beaulieu) figures...         PG-13   \\n1   Dr. Clayton Forrester (Trace Beaulieu) figures...         PG-13   \\n2   Dr. Clayton Forrester (Trace Beaulieu) figures...         PG-13   \\n3   A science-fiction film that combines tradition...            PG   \\n4   A science-fiction film that combines tradition...            PG   \\n..                                                ...           ...   \\n95  With the United States under the threat of nuc...             R   \\n96  Blurring the lines between reality and compute...         PG-13   \\n97  Blurring the lines between reality and compute...         PG-13   \\n98  After the Earth is conquered by alien robots, ...         PG-13   \\n99  In a dystopian society, single people must fin...             R   \\n\\n                                              Géneros  \\\\\\n0   Comedy, Science Fiction & Fantasy, Special Int...   \\n1   Comedy, Science Fiction & Fantasy, Special Int...   \\n2   Comedy, Science Fiction & Fantasy, Special Int...   \\n3   Animation, Kids & Family, Science Fiction & Fa...   \\n4   Animation, Kids & Family, Science Fiction & Fa...   \\n..                                                ...   \\n95  Comedy, Musical & Performing Arts, Mystery & S...   \\n96               Animation, Science Fiction & Fantasy   \\n97               Animation, Science Fiction & Fantasy   \\n98      Action & Adventure, Science Fiction & Fantasy   \\n99  Comedy, Cult Movies, Drama, Science Fiction & ...   \\n\\n                                           Directores  \\\\\\n0                                          Jim Mallon   \\n1                                          Jim Mallon   \\n2                                          Jim Mallon   \\n3                             Don Bluth, Gary Goldman   \\n4                             Don Bluth, Gary Goldman   \\n..                                                ...   \\n95                                      Richard Kelly   \\n96  Hironobu Sakaguchi, Motonori Sakakibara, Jack ...   \\n97  Hironobu Sakaguchi, Motonori Sakakibara, Jack ...   \\n98                                         Jon Wright   \\n99                                   Yorgos Lanthimos   \\n\\n                                              Autores  \\\\\\n0   Michael J. Nelson, Mary Jo Pehl, Bridget Jones...   \\n1   Michael J. Nelson, Mary Jo Pehl, Bridget Jones...   \\n2   Michael J. Nelson, Mary Jo Pehl, Bridget Jones...   \\n3                Ben Edlund, John August, Joss Whedon   \\n4                Ben Edlund, John August, Joss Whedon   \\n..                                                ...   \\n95                                      Richard Kelly   \\n96        Hironobu Sakaguchi, Al Reinert, Jeff Vintar   \\n97        Hironobu Sakaguchi, Al Reinert, Jeff Vintar   \\n98                              Jon Wright, Mark Stay   \\n99                Yorgos Lanthimos, Efthimis Filippou   \\n\\n                                              Actores Fecha estreno  Duración  \\\\\\n0   Michael J. Nelson, Trace Beaulieu, Jim Mallon,...    1996-04-19      73.0   \\n1   Michael J. Nelson, Trace Beaulieu, Jim Mallon,...    1996-04-19      73.0   \\n2   Michael J. Nelson, Trace Beaulieu, Jim Mallon,...    1996-04-19      73.0   \\n3   Matt Damon, Bill Pullman, Drew Barrymore, John...    2000-06-16      95.0   \\n4   Matt Damon, Bill Pullman, Drew Barrymore, John...    2000-06-16      95.0   \\n..                                                ...           ...       ...   \\n95  Seann William Scott, Sarah Michelle Gellar, Cu...    2007-09-22     144.0   \\n96  Ming-Na Wen, Alec Baldwin, Ving Rhames, Steve ...    2001-07-11     106.0   \\n97  Ming-Na Wen, Alec Baldwin, Ving Rhames, Steve ...    2001-07-11     106.0   \\n98  Ben Kingsley, Gillian Anderson, Callan McAulif...    2015-07-03      89.0   \\n99  Colin Farrell, Rachel Weisz, Léa Seydoux, Ben ...    2016-05-13     118.0   \\n\\n                  Productora  Similitud  \\n0   MCA Universal Home Video     0.5139  \\n1   MCA Universal Home Video     0.5139  \\n2   MCA Universal Home Video     0.5139  \\n3           20th Century Fox     0.5027  \\n4           20th Century Fox     0.5027  \\n..                       ...        ...  \\n95      Samuel Goldwyn Films     0.3816  \\n96         Columbia Pictures     0.3798  \\n97         Columbia Pictures     0.3798  \\n98    Vertical Entertainment     0.3783  \\n99                 A24 Films     0.3776  \\n\\n[100 rows x 13 columns].Dame la respuesta en base al contexto dado por el sistema de recuperacion de la informacion\', \'Claro, basándome en la información proporcionada por el sistema de recuperación, aquí tienes algunas películas de ciencia ficción que involucran tecnología avanzada:\\n\\n1.  **Titan A.E.** (Ranking 4, 5):\\n    *   **Información:** Es una película de ciencia ficción animada que se desarrolla en el año 3043, después de que la Tierra ha sido destruida. Esto implica la presencia de tecnología avanzada para la supervivencia espacial, naves interplanetarias y posiblemente armas futuristas, dada la necesidad de encontrar un nuevo hogar.\\n    *   **Géneros:** Animación, Ciencia Ficción y Fantasía.\\n    *   **Directores:** Don Bluth, Gary Goldman.\\n    *   **Año de estreno:** 2000.\\n\\n2.  **Final Fantasy: The Spirits Within** (Ranking 97, 98):\\n    *   **Información:** Esta película destaca por "difuminar las líneas entre la realidad y la computación", ambientada en el año 2065, donde la Tierra está siendo devastada por invasores alienígenas. La trama sugiere la utilización de tecnología avanzada para combatir a los alienígenas y la propia naturaleza de su animación de vanguardia es un ejemplo de tecnología.\\n    *   **Géneros:** Animación, Ciencia Ficción y Fantasía.\\n    *   **Directores:** Hironobu Sakaguchi, Motonori Sakakibara, Jack Fletcher.\\n    *   **Año de estreno:** 2001.\\n\\n3.  **Robot Overlords** (Ranking 99):\\n    *   **Información:** La premisa central es que la Tierra ha sido conquistada por robots alienígenas. Esto claramente sitúa la tecnología avanzada (robots, seguramente naves, sistemas de control, etc.) en el centro de la narrativa.\\n    *   **Géneros:** Acción y Aventura, Ciencia Ficción y Fantasía.\\n    *   **Director:** Jon Wright.\\n    *   **Año de estreno:** 2015.\\n\\nAunque otras películas como **Mystery Science Theater 3000: The Movie** (Ranking 1, 2, 3) se encuentran en el género de ciencia ficción y comedia, su descripción se centra más en una experimentación de un Dr. con películas que en tecnología avanzada en la trama principal. **The Lobster** (Ranking 100), aunque es ciencia ficción distópica, no detalla explícitamente tecnología avanzada en su sinopsis.\\n\\nEspero que estas recomendaciones te sean útiles. ¡Avísame si quieres saber más sobre alguna de ellas!\', \'Ya pero cual de esas es mas antigua\'])'

In [65]:
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=context,
)

print(response.text)

Claro, de las películas que te mencioné por su enfoque en tecnología avanzada:

*   **Titan A.E.** se estrenó en el año **2000**.
*   **Final Fantasy: The Spirits Within** se estrenó en el año **2001**.
*   **Robot Overlords** se estrenó en el año **2015**.

La más antigua de esas tres es **Titan A.E.**, estrenada en el año 2000.